config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "users/show"

  resources :users
  resources :wikis do
    resources :collaborators
  end
  resources :charges, only: [:new, :create]

  post 'users/downgrade'
  
  get 'welcome/index'
  get 'userpage', to: 'users#show', :as => :Wik

  root to: 'welcome#index'
  
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :wikis
  has_many :collaborators
  belongs_to :collaborators
  after_initialize :set_default_role, :if => :new_record?

  # show all users except user passed in 
  scope :all_except, ->(user) { where.not(id: user)}

  def self.public_wikis
    where(:private => false)
  end
  
  def admin?
    role == 'admin'
  end

  def standard?
    role == 'standard'
  end

  def premium?
    role == 'premium'
  end

  def set_default_role
    self.role ||= :standard
  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
  validates_presence_of :user_id
  default_scope { order('created_at DESC') }

  scope :publicly_visable, -> (user) { user ? all : where(:private => false) }
  scope :privately_visable, -> (user) { user ? all : where(:private => true) }

  def public?
    !self.private
  end

  def users
    arr = collaborators.collect(&:user).to_ary
    arr << user
    arr
  end

  def available_collaborators
    User.all.reject {|user| users.include?(user)}
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_filter :user

  rescue_from Pundit::NotAuthorizedError do |exception|
   redirect_to wikis_path, alert: exception.message
  end

  def after_sign_in_path_for(resource)
    wikis_path
  end

  private

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
  end

  def user
    @user = User.new
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     email: current_user.email,
     description: "Blocipedia Membership - #{current_user.name}",
     amount: 15_00
    }
  end

  def create

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => 15_00,
      :description => 'Blocipedia Membership',
      :currency    => 'usd'
    )

    current_user.update_attributes!(role: 'premium')

    if current_user.premium?
        redirect_to user_path(current_user)
    else
      flash[:error] = "There was an error upgrading your account. Please try again."
      redirect_to edit_user_registration_path
    end

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charges_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  def index
    @wiki = Wiki.find(params[:wiki_id])
    @collaborators  = @wiki.collaborators
    authorize @collaborators
  end

  def edit
  end

  def new
    @wiki = Wiki.find(params[:wiki_id]) # finds wiki from params
    @collaborator = @wiki.collaborators.new # creates new collaborator for wiki
    @collaborators = @wiki.collaborators # sets existing wiki collaborators
    @users = @wiki.available_collaborators
    # @users = User.all_except(@collaborators) && User.all_except(current_user) # sets users without existing wiki collaborators and current_user
  end

  def show
  end

  def create
    if Collaborator.exists?(collaborator_params[:user_id])
      redirect_to new_wiki_collaborator_path(@wiki)
    else
      @wiki = Wiki.find(params[:wiki_id])
      @collaborator = @wiki.collaborators.build(collaborator_params)
        if @collaborator.save
          flash[:notice] = "Collaborator added successfully"
          redirect_to wiki_collaborators_path(@wiki)
        else
        flash[:error] = "There was an error adding the collaborator. Please try again."
        redirect_to new_wiki_collaborator_path(@wiki)
      end
    end
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])
    if @collaborator.destroy
      flash[:notice] = "The collaborator was removed successfully."
      redirect_to wiki_collaborators_path
     else
      flash[:error] = "There was an error removing the collaborator. Please try again."
      render :show
     end
  end

  private

  def collaborator_params
    params.require(:collaborator).permit(:user_id, :wiki_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    @search = Wiki.search(params[:q])
    @wikis = @search.result
    @priwikis = Wiki.privately_visable(@user)
    @pubwikis = Wiki.publicly_visable(@user)
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    current_user.update_attributes!(role: 'premium')
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  def downgrade
    wikis = Wiki.all
    user = current_user
    user.role = 'standard'
    current_user.wikis.where(:private => true).update_all(:private => false)
    if user.save!

      redirect_to users_path
    else
      flash[:error] = "There was an error downgrading your user. Please try again."
      redirect_to edit_user_registration_path
    end
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
  
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

   def index
    @wikis = policy_scope(Wiki)
    # @wikis = @search.result.paginate(:page => params[:page], per_page: 10)
   end

  def new
    @wiki = current_user.wikis.new
    @user = current_user
    authorize @wiki
  end

   def show
    @wiki = Wiki.find(params[:id])
    @user = current_user
   end

   def edit
    @users = User.all
    @wiki = Wiki.find(params[:id])
    authorize @wiki
   end

   def create
    @wiki = Wiki.new(params.require(:wiki).permit(:title, :body, :private,))
    @wiki.user = current_user
    authorize @wiki
    if @wiki.save
      redirect_to @wiki
    else
      redirect_to :back
    end
   end

   def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    if @wiki.update_attributes(params.require(:wiki).permit(:title, :body, :public, :private, :user_id))
      redirect_to @wiki
    else
      flash[:error] = "There was an error saving the wiki info. Please try again."
      render :edit
      end
    end

    def destroy
     @wiki = Wiki.find(params[:id])
     authorize @wiki
     if @wiki.destroy
      flash[:notice] = "The wiki was removed successfully."
      redirect_to wikis_path
     else
      flash[:error] = "There was an error removing the wiki. Please try again."
      render :show
     end
   end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, :sort => column, :direction => direction, :class => css_class
  end
  
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<div class="h3-text-devise">
  <h3>Premium Membership</h3>
  <p>With this membership, users will be allowed to ceate private wikis</p>
  <div>
    <h3>only<strong> $15</strong></h3>
  </div>

  <%= form_tag charges_path do %>
    <script
      class='stripe-button' 
      src="https://checkout.stripe.com/checkout.js" 
      data-key="pk_test_W8hbNO9TwdEsxsRpD6vfmAsX"
      data-amount=<%= @stripe_btn_data[:amount] %> 
      data-name="Blocipedia"
      data-description="One Year Membership"
      data-email="<%= @stripe_btn_data[:email] %>">
    </script>
  <% end %>
</div>

app/views/collaborators/_form.html.erb
<%= form_for([@wiki, @collaborator]) do |f| %>
  <div class="field">
    <%= f.select 'user_id', (@users.collect{ |u| [u.name, u.id] }) %>
  </div>
  <div class="actions collaborator-button">
    <%= f.submit %>
  </div>
<% end %>

app/views/collaborators/edit.html.erb
<h1>Collaborators#edit</h1>
<p>Find me in app/views/collaborators/edit.html.erb</p>

app/views/collaborators/index.html.erb
<h1 class="h3-text-devise">"<%= @wiki.title %>" collaborators</h1>
<%= link_to 'New Collaborator', new_wiki_collaborator_path, class: 'btn btn-success' %>
<table class= "table table-bordered table-hover" data-sort-name="description" data-sort-order="desc">
  <thead>
    <tr>
      <th>User</th>
      <th>Added at</th>
      <% if current_user.id == @wiki.user_id %>
        <th></th>
      <% end %>
    </tr>
  </thead>

  <% if @collaborators.any? %>
    <tbody>
      <% @collaborators.each do |collaborator| %>
        <tr>
          <td><%= collaborator.user.name %></td>
          <td><%= collaborator.created_at %></td>
          <% if current_user.id == @wiki.user_id %>
              <td><%= link_to 'Delete', wiki_collaborator_path(@wiki, collaborator), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

<br>
<br>

  <%= link_to 'Back', wikis_path %>

app/views/collaborators/new.html.erb
<h1 class="h3-text-devise">Add Collaborators</h1>

<%= render 'form' %>

<%= link_to 'Back', wikis_path %>

app/views/collaborators/show.html.erb
<h1>Collaborators#show</h1>
<p>Find me in app/views/collaborators/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div>
      <% if current_user %>
        <ul class="blocipedia-icon pull-left">
          <p>
            <a href=<%= wikis_path %>>
              <img src="https://ujk-portfolio-development.s3.amazonaws.com/uploads/work/blocipedia/blocipedia.svg" style="float:left;width:100px;height:100px;">
            </a>
          </p>
        </ul>
      <% else %>
        <ul class="blocipedia-icon pull-left">
          <p>
            <a href=<%= welcome_index_path %>>
              <img src="https://ujk-portfolio-development.s3.amazonaws.com/uploads/work/blocipedia/blocipedia.svg" style="float:left;width:100px;height:100px;">
            </a>
          </p>
        </ul>
      <% end %>
    </div>
    
    <div>
      <ul class="nav nav-tabs pull-right">
        <% if current_user && current_user.role == 'standard' %>
          <li><%= link_to "Wikis", wikis_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to current_user.name, user_path(current_user) %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% elsif current_user && current_user.role == 'premium' || current_user && 
        current_user.role == 'admin' %>
          <!-- <li><%= link_to "Private Wikis", wikis_path %></li> -->
          <li><%= link_to "Wikis", wikis_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to current_user.name, user_path(current_user) %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Wikis", wikis_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>

    <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
    <% elsif flash[:error] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
    <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
    <% end %>
     
    <%= yield %>
  </div>
</body>
</html>

app/views/users/_user.html.erb
<% if (current_user) %>
  <td><%= link_to user[:name], user %></td>
  <td><%= user[:email] %></td>
  <td><%= user[:role] %></td>
  <% else %>
  <td>Please login to see list of users.</td>
<% end %>

app/views/users/_wiki.html.erb
<tr>
  <td><%= link_to wiki.title, wiki_path(wiki) %></td>
  <td><%= time_ago_in_words(wiki.created_at) %> ago by <%= wiki.user.name %></td>
  <% if current_user %>
    <td><%= link_to "edit", edit_wiki_path(wiki) %></td>
  <% end %>
</tr>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3 class="h3-text-devise">Users</h3>
    <div class="column">
      <table class= "table table-bordered table-hover" data-sort-name="description" data-sort-order="desc">
        <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Account Type</th>
        </tr>
      </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

app/views/users/show.html.erb
<div class="h3-text-devise">
  <h2><%= @user.name if @user.name %></h2>
  <p>Email: <%= @user.email if @user.email %></p>
  <p>Account Type: <%= @user.role %></p>
  <p><%= link_to "Edit User Info", edit_user_registration_path %></p>
  <%if current_user.premium? %>
    <div>
      <h3>Private Wikis</h3>
      <div>
        <table class= "table table-bordered table-hover" data-sort-name="description" data-sort-order="desc">
          <%= render partial: 'wikis/tableheaders' %>
          <tbody>
            <% @priwikis.each do |wiki| %>
              <%= render partial: 'wiki', locals: {wiki: wiki} %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
  <div>
    <h3>Public Wikis</h3>
    <div>
      <table class= "table table-bordered table-hover" data-sort-name="description" data-sort-order="desc">
        <%= render partial: 'wikis/tableheaders' %>
        <tbody>
          <% @pubwikis.each do |wiki| %>
            <%= render partial: 'wiki', locals: {wiki: wiki} %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<body class="welcome-index">
  <div class="row buffer">
    <div class="col-md-12 text-center">
      <div class="col-md-6 col-md-offset-3 home-page-intro">
        <h3 class= "h3-text">Create and share Markdown Wikis</h3>
        <div class="form-group">
          <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-info btn-lg' %>
        </div>
      </div>
    </div>
  </div>
</body>

<!-- <div class-"col-md-12 text-left">
  <div class="cold-md-9 col-md-offset-2">
    <p>Create as many public wikis as you want!</p>
  </div>
</div>
<div class-"col-md-12 text-right">
  <div class="cold-md-9 col-md-offest-2">
    <p>Create private wikis!</p>
  </div>
</div> -->

app/views/wikis/_form.html.erb
<div>
  <%= f.check_box :private %> Private wiki
</div>

app/views/wikis/_tableheaders.html.erb
<thead>
  <tr>
    <th><%= sort_link @search, :title, "Wiki Name" %></th>
    <th><%= sort_link @search, :created_at, "Created at" %></th>
    <% if current_user %>
      <th colspan="4"></th>
    <% end %>
  </tr>
</thead>

app/views/wikis/_wiki.html.erb
<tr>
  <td><%= link_to wiki.title, wiki_path(wiki) %></td>
  <td><%= time_ago_in_words(wiki.created_at) %> ago by <%= link_to wiki.user.name, user_path(wiki.user) %></td>
  <% if @user.premium? || @user.admin? %>
    <td><%= link_to 'View Collaborators', wiki_collaborators_path(wiki) %></td>
    <td><%= link_to 'Add Collaborator', new_wiki_collaborator_path(wiki) %></td>
    <td><%= link_to 'Delete', wiki, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% elsif current_user %>
    <td><%= link_to "Edit", edit_wiki_path(wiki) %></td>
    <td><%= link_to 'Delete', wiki, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</tr>

app/views/wikis/edit.html.erb
<h2 class= "h3-text-devise">Edit</h2>

<div class="col-md-8">
  <%= form_for @wiki do |f| %>
  <% if current_user.role == 'admin' || current_user.role == 'premium' %>
    <%= render partial: 'form', locals: {f: f} %>
    <%= link_to 'New Collaborator', new_wiki_collaborator_path(@wiki) %>
    <br>
    <%= link_to 'View Collaborators', wiki_collaborators_path(@wiki) %>
  <% end %>
  <br>
  <br>
   <div class="form-group">
     <%= f.label :name %>
     <%= f.text_field :title, class: 'form-control', placeholder: "New Wiki name" %>
   </div>
   <div class="form-group">
     <%= f.label :description %>
     <%= f.text_area :body, rows: 5, class: 'form-control', placeholder: "New Wiki description" %>
   </div>
   <%= link_to "Back", :back, class: 'btn btn-info' %>
   <%= f.submit "Save", class: 'btn btn-success' %>
   <%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>
 <% end %>
</div>

app/views/wikis/index.html.erb
<div class="container">
  <div class="row buffer">
    <h2 class= "h3-text-devise">Wikis</h2>
    <div class="new-wiki-btn">
      <%if current_user %>
      <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
      <% end %>
    </div>
    <table class= "table table-bordered table-hover" data-sort-name="description" data-sort-order="desc">
      <%# render partial: 'tableheaders' %>
      <tbody>
        <% @wikis.each do |wiki| %>
          <%= render partial: 'wiki', locals: {wiki: wiki} %>
        <% end %>
      </tbody>
    </table>
    <div class="apple_pagination">
      <%# will_paginate @wikis %>
    </div>
  </div>
</div>

app/views/wikis/new.html.erb
<h2 class= "h3-text-devise">Create a new Wiki</h2>

<div class="col-md-8">
  <%= form_for @wiki do |f| %>
   <% if current_user.role == 'admin' || current_user.role == 'premium' %>
    <%= render partial: 'form', locals: {f: f} %>
   <% end %>
   <div class="form-group">
     <%= f.label :name %>
     <%= f.text_field :title, class: 'form-control', placeholder: "New Wiki name" %>
   </div>
   <div class="form-group">
     <%= f.label :description %>
     <%= f.text_area :body, rows: 5, class: 'form-control', placeholder: "New Wiki description" %>
   </div>
   <%= f.submit "Create Wiki", class: 'btn btn-success' %>
 <% end %>
</div>

app/views/wikis/show.html.erb
<div>
  <h1 class= "h3-text-devise"><%= markdown_to_html @wiki.title %></h1>
  <p><%= markdown_to_html @wiki.body %></p>
   <div>
    <% if current_user %>
      <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-info' %>
      <%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>
    <% end %>
   </div>
</div>